apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: goldengoose
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: goldengoose
      track: prod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: goldengoose
        track: prod
    spec:
      containers:
      - image: dippynark/goldengoose
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: goldengoose
        ports:
        - containerPort: 8000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        app: goldengoose
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: goldengoose
  namespace: default
spec:
  clusterIP: 10.23.252.14
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32181
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: goldengoose
    track: prod
  sessionAffinity: None
  type: LoadBalancer
