apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: sock-shop
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - www.nachocanon.tk
    secretName: front-end-tls
  rules:
  - host: www.nachocanon.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: front-end
          servicePort: 80
